apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: "azure-identity"
spec:
  type: 0
  resourceID: "/subscriptions/xxxxxxxxxxx/resourcegroups/AZDEV-RG-AKSPOC-EASTUS-001/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxxxxxx"
  clientID: "xxxx-52d6-xxxx-970d-xxxxxxx"
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: "azure-identity-binding"
spec:
  azureIdentity: "azure-identity"
  selector: "azure-keyvault"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "xxxxx"
    userAssignedIdentityID: "/subscriptions/xxxxxxxxxxx/resourcegroups/AZDEV-RG-AKSPOC-EASTUS-001/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxxxxxx"
    cloudEnv: |
      {
        "name": "AzurePublicCloud",
        "keyVaultDNSSuffix": "xxxxxxx"
      }
    objects: |
      - objectName: authority
        objectType: secret
      - objectName: audience
        objectType: secret
      - objectName: encryptionKey
        objectType: secret
tenantId: "xxxxx-daad-xxx-9ec4-xxxxxxx"
---