// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.telefono;
using api.telefono.Database;

#nullable disable

namespace api.telefono.Migrations
{
    [DbContext(typeof(TelefonosDbContext))]
    partial class TelefonosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.telefono.Models.Telefono", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Operadora")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Telefonos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c37d2c81-e592-4de5-96db-e0976fa8cbcd"),
                            IdCliente = new Guid("f2168584-457f-18d7-f563-d46069d03998"),
                            Numero = "09-705-138-667",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("25ec6419-b0c3-4a1f-bc06-6c8c7eef97f6"),
                            IdCliente = new Guid("fc90924f-7506-90a5-af8a-4628f1dfdc8a"),
                            Numero = "06-940-091-387",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("ff58dde5-a0ff-4490-9297-e7e9f2534792"),
                            IdCliente = new Guid("8dab723c-5d64-964e-8fa1-6e0aa2e1de14"),
                            Numero = "08-444-872-377",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("63a2fb3a-eaf3-4fef-acbe-99c5faaca12c"),
                            IdCliente = new Guid("0f0ed5b7-0c60-f8bf-37ce-8f9bf524ff7f"),
                            Numero = "09-339-182-523",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("e8e0427c-b65a-4db4-8684-49c9541e3d55"),
                            IdCliente = new Guid("e56dd9d9-ba2b-92da-f2a5-9836e53729ed"),
                            Numero = "01-623-342-180",
                            Operadora = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("94ba0584-7781-4e1e-8101-245a031a0e8f"),
                            IdCliente = new Guid("cb2349c9-5daa-a3e1-27f4-fd8a5eb516ba"),
                            Numero = "04-092-230-859",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("4e973d8e-f5eb-49aa-a54e-9e74887e72b5"),
                            IdCliente = new Guid("5a71f042-c594-94fc-c8da-6dfc951b16ee"),
                            Numero = "02-194-771-470",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("fdfcd8a0-3b95-467a-9abd-2afee1fdfe16"),
                            IdCliente = new Guid("6e535878-c284-f51e-d64e-d0f69ffa9edd"),
                            Numero = "00-149-031-397",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("09fe5056-73d4-4e2a-add6-bd2cde782990"),
                            IdCliente = new Guid("f23d65af-5641-95e0-0dcb-d1415c2d988e"),
                            Numero = "01-601-334-555",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("e4ceb1d7-e104-44eb-831a-fec4e594a55e"),
                            IdCliente = new Guid("cb6409c8-0de4-fb1d-e1c1-913d016f0a09"),
                            Numero = "09-098-638-283",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("e0a497e0-0e70-4fbd-ab81-d2e6e32eef4c"),
                            IdCliente = new Guid("3dd8f5fa-36f7-25b8-34ae-450eb5621d63"),
                            Numero = "06-439-407-156",
                            Operadora = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("8af0c0f9-d51e-4348-9e87-7bd9f0d3629d"),
                            IdCliente = new Guid("2df36e52-d12b-491c-2917-9bb96fb334bf"),
                            Numero = "03-535-283-722",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("b476dce7-fa74-478b-9643-ab4c1de54618"),
                            IdCliente = new Guid("e0d3d86f-0f1e-e0a6-f1a7-8da6c289c40a"),
                            Numero = "05-820-377-107",
                            Operadora = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("7866b6f6-3b76-4a96-ad78-ac3609641a2f"),
                            IdCliente = new Guid("2d545dc6-73de-a59c-c6b4-1671d11161ca"),
                            Numero = "06-014-861-710",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("7cd28d5d-34e1-44db-87f2-966d8feb05ed"),
                            IdCliente = new Guid("36390d88-5dc2-55e6-5cde-828fd9a046f0"),
                            Numero = "02-304-252-132",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("8694e88a-f050-45ac-a3a8-ca087e6d3c06"),
                            IdCliente = new Guid("5bc5df73-5011-58f1-8770-569113745d6d"),
                            Numero = "06-491-548-905",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("74f710e2-e989-472b-a3dd-bfd8c00b7d9f"),
                            IdCliente = new Guid("0eeab85c-2950-3253-e248-0a3e06289b67"),
                            Numero = "06-665-206-694",
                            Operadora = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("d058b7cd-00cd-4f2b-b2d4-7df7fbc4ed7a"),
                            IdCliente = new Guid("65a9550b-4d77-5a6e-9c86-2956e1d9ffc8"),
                            Numero = "09-693-775-515",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("9d9839e4-fa5b-4a5d-afb8-f1c2c26442df"),
                            IdCliente = new Guid("5e100eed-12db-4106-2078-fef0006008d5"),
                            Numero = "01-702-154-220",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("1170ad27-5468-4534-a360-2c3cb7b4c4f0"),
                            IdCliente = new Guid("7085457f-207c-256c-3340-580aeb0fa9f3"),
                            Numero = "03-044-735-784",
                            Operadora = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("64591c75-1afb-4959-a981-5fae19b68e72"),
                            IdCliente = new Guid("2d6757ad-0858-1406-fb3c-27d1d13b32d5"),
                            Numero = "02-195-564-561",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("c2e4dc15-48be-452d-8704-6e5d7bf0712f"),
                            IdCliente = new Guid("7df3f0b1-141f-593b-1a4e-fbd51aa959fd"),
                            Numero = "09-807-924-937",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("d0940f54-2b05-45f4-98dc-d8ca5fdfd70b"),
                            IdCliente = new Guid("a0ebf794-3589-60bc-2482-6caa42c2113c"),
                            Numero = "03-709-422-342",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("8f7ddbba-345c-4dd7-9cd4-5895cf82a81b"),
                            IdCliente = new Guid("0c90f048-2c41-5c40-2ebb-e48ef5117367"),
                            Numero = "08-749-830-475",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("fb5b0b1a-8cce-4f4c-9e65-ed77f8fa108d"),
                            IdCliente = new Guid("90b6968d-5566-b549-2417-2b200383dcf7"),
                            Numero = "08-837-237-411",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("f021f2dc-aa08-467f-ba7a-178247b44e60"),
                            IdCliente = new Guid("73ce1fcc-1065-b685-2b71-2f43c6aa6363"),
                            Numero = "07-901-759-240",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("02fa36f2-6737-41e2-97db-87cd66167254"),
                            IdCliente = new Guid("df051501-395e-9edc-c7e8-2d09ec3a16d1"),
                            Numero = "05-896-228-706",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("b0588e63-ecbb-4958-a34c-5fe746dc53a4"),
                            IdCliente = new Guid("7fbbb29d-8148-e893-7454-7ade182727d4"),
                            Numero = "00-806-632-708",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("fbe41d4b-9e94-4b85-b689-a24ad565a152"),
                            IdCliente = new Guid("740c1137-be24-e8a2-1626-f607d33d9c09"),
                            Numero = "04-268-720-196",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("5daa11a9-3a9c-41bb-978e-3da4af330489"),
                            IdCliente = new Guid("779055a4-22d8-68cd-2d92-b2e176f9b5ff"),
                            Numero = "02-768-631-281",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("15c37a7f-5949-449a-8b00-248f5d5e9ae5"),
                            IdCliente = new Guid("db3c5ba5-1b47-436d-5158-935d17b9e219"),
                            Numero = "00-992-136-671",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("6d954a33-9a28-4a33-8228-0588d0747a6a"),
                            IdCliente = new Guid("7a0efd61-7629-9557-0402-5d3173427539"),
                            Numero = "00-855-552-859",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("0c7074b4-6ae1-4c28-a425-d7d805e097f7"),
                            IdCliente = new Guid("e0dd95a6-0a30-f65f-1594-c092d3359089"),
                            Numero = "05-509-832-643",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("1a74ef53-3186-4468-b707-4bcf0d6a3ee8"),
                            IdCliente = new Guid("05b3007a-e304-a09e-152c-99302f0b077c"),
                            Numero = "09-674-531-911",
                            Operadora = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("970c6d75-bdc8-43be-b624-fb5b60bb666c"),
                            IdCliente = new Guid("63f7d292-860d-4759-6306-9f1fa6bd3671"),
                            Numero = "09-570-995-585",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("bcd61b31-fda9-43be-b5b1-a62788dd4ac9"),
                            IdCliente = new Guid("46d9d069-5b62-db5d-f813-8923c6b0e0ac"),
                            Numero = "04-054-915-575",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("8445279c-11aa-4c45-bff6-2c7829d63c53"),
                            IdCliente = new Guid("79dbb017-a597-6b5a-d64c-9f9eaaa3cbdf"),
                            Numero = "03-314-414-871",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("68802895-82ab-4f15-98bd-e79b933ef511"),
                            IdCliente = new Guid("4b667aeb-6765-9c15-aa9b-699c159bbf35"),
                            Numero = "04-044-109-721",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("df564627-6817-4e78-ad9f-83b40a566389"),
                            IdCliente = new Guid("84d1c415-62df-d9e7-a649-fdf97d48ad8a"),
                            Numero = "00-283-315-669",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("4f3208d4-cd35-4093-8ab5-2de133a516df"),
                            IdCliente = new Guid("3eb14d44-346e-a263-5447-41c1436ac427"),
                            Numero = "03-045-964-841",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("c3caa8b1-a84e-44ba-b215-ebe8a57f1fed"),
                            IdCliente = new Guid("b6fb276c-8712-9f2a-43d9-d9b8a1d1a1f0"),
                            Numero = "08-114-856-670",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("92a96e66-6973-43f9-81cd-3d17fe8652bf"),
                            IdCliente = new Guid("b5c07805-d5bf-c6e6-e32e-6ed5a474670a"),
                            Numero = "07-400-123-508",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("86fdbdfd-2d99-4c5d-a7b0-0571bb820e06"),
                            IdCliente = new Guid("4f81e8b0-1437-f72a-5274-d4c4e39753d4"),
                            Numero = "08-264-086-735",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("88d11958-b429-45df-a1f9-959fb1a58749"),
                            IdCliente = new Guid("d805e24a-90b0-e89a-e8d7-5f10f44696ec"),
                            Numero = "01-056-365-425",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("1a74d2c6-f709-49aa-81d9-ebb52846d082"),
                            IdCliente = new Guid("eee621de-ec7c-56c8-1e54-10a25eda030d"),
                            Numero = "03-083-651-637",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("ae3fe8f1-56d7-4abd-b787-567e470b094e"),
                            IdCliente = new Guid("a413f325-b803-0f65-1fd5-f14b0d4dfbf8"),
                            Numero = "07-880-366-452",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("f96ed829-a2fd-4a0b-9bac-71d918774447"),
                            IdCliente = new Guid("3b0ff909-3e94-b9f4-ced6-f0d30e48b40f"),
                            Numero = "09-651-668-702",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("bef179e2-04e9-4705-8779-395e24011078"),
                            IdCliente = new Guid("214b9c40-637b-ca01-437a-81f284633390"),
                            Numero = "05-085-976-347",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("16c146f1-f4a7-43c4-9b22-7e8bc81d612c"),
                            IdCliente = new Guid("0a20ad77-8a5d-3e63-b01f-5ef7861224a1"),
                            Numero = "01-073-191-621",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("09344f11-b5f3-440b-b2f6-63cc3dd4c314"),
                            IdCliente = new Guid("4fb82775-9e32-be46-a9d9-de1b2dd45431"),
                            Numero = "05-917-525-861",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("a5eb8b61-74e6-4861-aa7d-f2781e8d8d08"),
                            IdCliente = new Guid("27f84d45-4339-dfdb-23ec-359078dd4e52"),
                            Numero = "09-331-530-720",
                            Operadora = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("a404f63a-dd28-40fd-acba-d5e24a0dd955"),
                            IdCliente = new Guid("58156cc5-2b99-5824-2000-324378333c0a"),
                            Numero = "03-278-374-846",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("5e8000f7-82d4-4dc2-8c5b-6c3bc401a42e"),
                            IdCliente = new Guid("d4535d27-bb52-d443-939a-701800a2e630"),
                            Numero = "08-531-201-473",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("63ab728a-428b-47f9-8cb9-729c133c14a8"),
                            IdCliente = new Guid("487bb131-0b63-015d-0be3-6c97827f7c0e"),
                            Numero = "03-671-477-428",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("9ba54476-8e1c-4f22-b6a2-970c79966f19"),
                            IdCliente = new Guid("97d848aa-e74f-0d47-a351-4587452916e8"),
                            Numero = "00-709-873-235",
                            Operadora = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("69e5903a-07f4-4783-9bc4-170563976867"),
                            IdCliente = new Guid("2eacc6c2-f158-29d5-93fa-9466de3b2db2"),
                            Numero = "07-691-005-169",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("89c4cc5f-544d-4052-b3c7-c216cb0e2b6c"),
                            IdCliente = new Guid("984ccefe-ee18-03e3-0246-6bd498831bb9"),
                            Numero = "09-780-003-877",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("f1a4d8ee-a11d-41ac-b310-7da258fe5a4c"),
                            IdCliente = new Guid("49cff53b-9222-7017-aa1c-ea889a74a149"),
                            Numero = "05-397-494-004",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("e347e216-717c-4106-b8db-4fcd5414be6d"),
                            IdCliente = new Guid("69111ed9-c4c3-4c95-43bc-89fdbdc4419d"),
                            Numero = "02-855-076-528",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("506bcc71-59b7-4622-ae41-dce68b910667"),
                            IdCliente = new Guid("61b2ee52-cb90-607c-b0cf-ba2b0b0bd0f7"),
                            Numero = "03-872-822-892",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("0b24a920-aaed-4ec5-a166-7fe0f99ef5c7"),
                            IdCliente = new Guid("9aafdd84-3424-28ee-bb84-8f634f79c82b"),
                            Numero = "04-563-678-397",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("81539739-97b4-4fcb-b221-fab9d533b025"),
                            IdCliente = new Guid("3fbbb959-313a-464a-2ed8-ddfebbe4ccd0"),
                            Numero = "00-573-285-868",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("433399be-e27c-4296-82fd-d3d24ee3bb96"),
                            IdCliente = new Guid("379c7d70-75f1-e74b-a9a3-74dc1c135988"),
                            Numero = "04-785-202-552",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("36dcebd9-ba07-482d-96cb-6e1ddab5e8e7"),
                            IdCliente = new Guid("d7b0a339-ed52-d2b1-0afa-6ed02a641a5a"),
                            Numero = "04-765-351-709",
                            Operadora = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("abbfaaa8-d570-45bb-9d8f-1f5311c99a46"),
                            IdCliente = new Guid("1cc17c20-f013-3309-04c8-74cdb85fe8ec"),
                            Numero = "06-045-558-999",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("c250a967-581d-44d9-bc82-ccf4bd7be18f"),
                            IdCliente = new Guid("7e37faed-aaca-1a15-9333-40a16df5baf4"),
                            Numero = "07-507-246-173",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("2aa5d2ee-52cf-4507-9871-c43f209de99d"),
                            IdCliente = new Guid("94742ce7-95da-c438-f431-bb8d0d8db015"),
                            Numero = "09-539-036-828",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("37ddf6b1-a959-4c8f-94b9-d055d44039ce"),
                            IdCliente = new Guid("4fd6a6a4-8b75-805b-44ee-d8bb2dacc673"),
                            Numero = "01-663-840-678",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("0a07aa67-a742-448e-a8fd-5832f6824e24"),
                            IdCliente = new Guid("6754e126-59c0-0138-7e09-9a6412818c12"),
                            Numero = "05-287-367-352",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("8754c37b-e4a9-4ab3-ab2b-2309ad87d8ef"),
                            IdCliente = new Guid("3710e0bb-306d-6b49-d742-e1949bc327b2"),
                            Numero = "08-156-854-089",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("9221fa5d-71e9-4128-b036-63af304e086d"),
                            IdCliente = new Guid("b972cc90-2716-e9e3-70b9-7e92fb4470f8"),
                            Numero = "08-480-744-401",
                            Operadora = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("87fd8721-c436-4b2a-becd-f175e0ccb14e"),
                            IdCliente = new Guid("7cf5d9ce-2611-cc45-145f-9b761623e501"),
                            Numero = "09-858-560-611",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("1ed2cc06-7f51-4803-98cb-a75b673e8ce3"),
                            IdCliente = new Guid("eb5dfdfb-b947-1852-884f-9fbc8393c268"),
                            Numero = "00-028-117-515",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("84991de9-c2a3-4fad-a689-66aea18f04c6"),
                            IdCliente = new Guid("26a5eb8b-d3b7-e89b-466e-7ca25c0560a9"),
                            Numero = "06-394-521-322",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("df686b7e-4a29-4589-b982-cffc9b42bede"),
                            IdCliente = new Guid("38c649bf-3213-2447-66d1-b7ea7b7d9b75"),
                            Numero = "01-187-416-700",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("d8514bb7-5299-4d73-a2b6-5ac6a46b4105"),
                            IdCliente = new Guid("33b41c29-196a-67e9-5992-182f72e8df7e"),
                            Numero = "02-071-526-102",
                            Operadora = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("a7db2f9d-36b0-42ee-b9d8-7e71ace088bb"),
                            IdCliente = new Guid("92d91f87-0273-fdb1-e58f-6703d98756f1"),
                            Numero = "02-566-119-329",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("1ddb0647-0867-4bd2-8062-014d7da87857"),
                            IdCliente = new Guid("4ef26e19-2cee-9c75-72ad-70c8a4c37749"),
                            Numero = "01-939-106-667",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("5c6e52d4-9cf2-43f5-8f35-db843fbdfbb1"),
                            IdCliente = new Guid("127610dd-7d11-b228-236b-defd83c885a1"),
                            Numero = "01-274-148-884",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("89a95a15-f821-43e1-abdb-1f07c8fa97fc"),
                            IdCliente = new Guid("528482ee-c76b-33e2-3eb6-2bd4a885abb9"),
                            Numero = "09-939-779-935",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("f1347e74-d9f9-42ba-972a-5f2f761f1db3"),
                            IdCliente = new Guid("7b8ab9e3-2fc6-7beb-e2d3-94b803318447"),
                            Numero = "07-427-503-152",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("cd029800-86c5-47db-835e-3a80d1249687"),
                            IdCliente = new Guid("f06feb6f-2366-4460-e364-10061d600862"),
                            Numero = "03-333-567-359",
                            Operadora = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("92f56f69-ebb0-46ab-be0b-892513cbc521"),
                            IdCliente = new Guid("0b690921-f012-3945-d29f-1715bd2ae2d6"),
                            Numero = "02-381-869-312",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("ac916d8d-dbec-43ac-bbcb-cdf6ed33ed0f"),
                            IdCliente = new Guid("711b3993-e491-f026-bafc-69bd83ae1a16"),
                            Numero = "09-687-605-259",
                            Operadora = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("1e7519aa-d187-408d-a6ce-b9aac4148f65"),
                            IdCliente = new Guid("2b2ed985-bfc1-c9e4-e269-ea1ea7a6d7ef"),
                            Numero = "03-854-065-997",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("ac27460b-74af-4967-9c33-9bfa547b5eac"),
                            IdCliente = new Guid("837f2164-b775-136d-84fb-3d53a03158e2"),
                            Numero = "04-967-977-696",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("bed411f4-4cb9-4410-b70b-771462cba769"),
                            IdCliente = new Guid("c8229ce9-397e-cab3-72c8-3dd9e6c4f59e"),
                            Numero = "02-995-740-961",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("3134b4d8-f335-4d6f-842e-9795a95cc5e5"),
                            IdCliente = new Guid("d408eabd-a25a-d4b5-ef07-ce4a3ba704cc"),
                            Numero = "01-895-073-952",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("1369453b-de26-474b-a751-b4005e79803c"),
                            IdCliente = new Guid("2e608ec6-280b-d4fe-cc4e-6e2e349b032b"),
                            Numero = "03-019-264-945",
                            Operadora = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("18911cc4-aa08-468f-89cc-0cc108b2b7e9"),
                            IdCliente = new Guid("b4264b21-b24b-734c-e303-eca201c82406"),
                            Numero = "02-499-206-959",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("507cf962-18eb-4611-8773-fea4257badc7"),
                            IdCliente = new Guid("5372d61d-134d-7a75-571c-1cedb2896e2c"),
                            Numero = "03-889-431-578",
                            Operadora = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("618a75ad-1363-4368-90f5-15b59984ef02"),
                            IdCliente = new Guid("6ca3182a-6d19-6a16-6cc9-1e59b97769f2"),
                            Numero = "05-465-914-487",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("b1124917-d3cd-4925-914c-4565d56443bc"),
                            IdCliente = new Guid("60101ba3-4373-eb31-ef77-72c1a7252d22"),
                            Numero = "01-255-224-671",
                            Operadora = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("f4d7662e-2d65-430d-8f1d-5a923bde6792"),
                            IdCliente = new Guid("ea5798c9-0c00-b5e3-1593-eac39e5c0294"),
                            Numero = "09-635-187-224",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("2f072408-b1e2-4c02-9ab8-c27623868fa9"),
                            IdCliente = new Guid("5533c8fa-7f2f-fc8f-25df-486a57c175e0"),
                            Numero = "08-194-519-027",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("402088cb-a0fe-4c30-86e4-f13c53e2a545"),
                            IdCliente = new Guid("44f0519c-aec4-336b-11ce-6ac4430c54c4"),
                            Numero = "07-908-597-306",
                            Operadora = 0,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("afbd03a9-d013-40a4-8023-0742f21dc631"),
                            IdCliente = new Guid("9e97f48a-6c9c-da3f-9995-38e2e0f02412"),
                            Numero = "05-536-380-965",
                            Operadora = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("8877c51c-540e-4202-b974-dafffa3eb6f8"),
                            IdCliente = new Guid("c050b66d-5dd7-a6d4-3f7e-6616d3bd4c3f"),
                            Numero = "08-522-978-128",
                            Operadora = 3,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("f4c75712-e93b-4b31-a383-b332b4653e04"),
                            IdCliente = new Guid("bdcdb319-1142-3595-c98d-3a69b6586e28"),
                            Numero = "09-012-909-870",
                            Operadora = 2,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("2e12868e-ef6c-47d3-9d9b-ddd920980fae"),
                            IdCliente = new Guid("6973d4ce-ab1a-2927-667b-230d931085a9"),
                            Numero = "00-208-973-224",
                            Operadora = 0,
                            Tipo = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
